### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by lemoer** [fenhl/Python-IRC-Bot-Framework#4]
I locally hacked the IPv6 support by changing the following line:

``` diff
- self.irc = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
+ self.irc = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
```

But this is not a nice solution since the library now has no more option to connect to an IPv4 server. It would be nice, if the library would be able to handle both IP versions automatically.

**Ideas:**
* Use ```ipaddress.ip_address(self.network).version``` to determine the IP version (if ```self.network``` is an IP-Address)
* Use the dns result for hostnames (by prefering IPv6 over IPv4)

**Comment by fenhl** [comment]
@lemoer Thanks for the suggestion, I have now implemented this. If you find any bugs, please do open issues for them, as I currently don't have the time to test this.
